{...}: {
  imports = [
    ./packages
  ];
  perSystem = {
    config,
    self',
    inputs',
    pkgs,
    system,
    ...
  }: {
    devenv.shells.default = {
      name = "DevEnv for publishing notes";
      git-hooks.hooks = {
        # lint shell scripts
        shellcheck.enable = true;
        # lint nix files
        alejandra.enable = true;

        trim-trailing-whitespace = {
          enable = true;
          excludes = [
            "^\\.gitignore$"
          ];
        };
        end-of-file-fixer.enable = true;
        # `publish` converts post images to WebP; anything over 1 MB after
        # that wasn't optimized.
        check-added-large-files = {
          enable = true;
          args = ["--maxkb=1024"];
        };
        check-yaml.enable = true;
        check-toml.enable = true;
        # content/notes and content/posts are generated by `publish` from the
        # vault, which is where pages are edited.
        markdownlint = {
          enable = true;
          excludes = ["^content/"];
        };
        treefmt = {
          enable = true;
          settings.formatters = [
            pkgs.alejandra
            self'.packages.mdformat
          ];
        };
      };

      # https://devenv.sh/reference/options/
      packages = [
        pkgs.hugo
        self'.packages.publish
      ];

      languages.go.enable = true;

      # disable containers
      containers = pkgs.lib.mkForce {};
    };
  };
}
