name: Publish blog/zet/notes
on:
  workflow_dispatch:
  schedule:
    - cron: "0 2 * * *"
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/checkout@v4
      with:
        fetch-depth: 1
        repository: hurricanehrndz/zet
        path: zet
        token: ${{ secrets.ZET_GH_PAT }}

    - uses: cachix/install-nix-action@v27
      with:
        github_access_token: ${{ secrets.GITHUB_TOKEN }}
    - run: nix develop --no-pure-eval --accept-flake-config --command build-content
    - run: nix develop --no-pure-eval --accept-flake-config --command hugo build -b https://hrndz.me/
    - uses: cloudflare/wrangler-action@v3
      with:
        apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
        accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
        command: pages deploy public --project-name=hrndz-me
