name: Publish blog/zet/notes
on:
  workflow_dispatch:
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/checkout@v4
      with:
        fetch-depth: 1
        repository: hurricanehrndz/zet
        path: zet
        token: ${{ secrets.ZET_GH_PAT }}

    - uses: cachix/install-nix-action@v27
      with:
        github_access_token: ${{ secrets.GITHUB_TOKEN }}
    - run: nix develop --no-pure-eval --accept-flake-config --command build-content
    - run: nix develop --no-pure-eval --accept-flake-config --command hugo build -b https://hrndz.me/
    - uses: cloudflare/wrangler-action@v3
      with:
        apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
        accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
        command: pages deploy public/ --project-name=hrndz-me
    - run: nix develop --no-pure-eval --accept-flake-config --command hugo build -b https://hrndz.dev/
    - name: Upload to S3
      run: |
        aws s3 sync ./public/ ${HRNDZ_DEV_BUCKET_URI}
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        HRNDZ_DEV_BUCKET_URI: ${{ secrets.HRNDZ_DEV_BUCKET_URI }}
        AWS_DEFAULT_REGION: 'us-east-1'
    - name: Publish to amplify via S3
      run: |
        aws amplify start-deployment --app-id ${HRNDZ_DEV_APP_ID} --branch-name staging --source-url ${HRNDZ_DEV_BUCKET_URI} --source-url-type BUCKET_PREFIX
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        HRNDZ_DEV_BUCKET_URI: ${{ secrets.HRNDZ_DEV_BUCKET_URI }}
        HRNDZ_DEV_APP_ID: ${{ secrets.HRNDZ_DEV_APP_ID }}
        AWS_DEFAULT_REGION: 'us-east-1'
